### ISSUE TITLE
Decide whether this is for desktops or mobile

### ISSUE THREAD

**Issue by probonopd** [maui-project/index#8]
> works on desktops, Android and Plasma Mobile.

As Steve Jobs said, you can't be everybody's darling all the time. So I'd say decide to make the best file manager for desktops, and leave it at that.

Windows 8 tried to be on mobiles and on desktops, and flopped. No one liked its tiles.

For example, "hamburger" menus are great on mobiles but not on desktops.

https://medium.com/@probonopd/make-it-simple-linux-desktop-usability-part-1-5fa0fb369b42

**Comment by milohr** [comment]
Hi.
The plans for the Maui project is convergence.
Index will use kde technologies on linux gnu distros to make it powerful, such as Baloo and KIO and others.
However on the its simpler form it could still be used on Android just fine.

On Plasma mobile it would take advantage of the same kde frameworks as on the desktop.

The challenge here is to be able to come up with a good design that works well on both type of devices, and that's big part of the reason i find interesting to work on this project, so i would rather to continue to work on that vision than just give it up.

I'm more than open and willing to take advices and review the design to end up with a better one.
To be honest, and it is my own opinion, so far Index ui/ux design works well for me, both on my android phone and my linux desktop, even when it still lacks tons of features but they will be coming in slowly.

Nice reading about btw. :)
